<?php echo $url;?>

<?php echo $parentId;?>

<?php
$title = 'Add Comment';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('comment_controller', array('action' => 'process')));
$form->prepare();

echo $this->form()->openTag($form) . PHP_EOL;
echo $this->formHidden($form->get('url')) . PHP_EOL;
echo $this->formRow($form->get('comment')) . PHP_EOL;
echo $this->formInput($form->get('submit')) . PHP_EOL;
echo $this->form()->closeTag($form) . PHP_EOL;