<?php echo $url; ?>

<table class="table">
    <thead>
        <tr>
            <th>#</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Username</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($list as $comment){ ?>
            <tr>
                <td><?= $comment->getCommentId() ?></td>
                <td><?= $comment->getProjectId() ?></td>
                <td><?= $comment->getComment() ?></td>
                <td><?= $comment->getDtc() ?></td>
            </tr>
        <?php } ?>
    </tbody>
</table>