<?php

namespace Comment\Repository;

use Doctrine\ORM\EntityRepository;
use Application\Entity\User;
use Application\Entity\Project;

//use Comment\Entity;
/**
 * Question
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Comment extends BaseRepositoryAbstract
{
    
    public function getUserComments(User $user)
    {
        $query = $this->_em->createQuery("SELECT u FROM Application\Entity\Comment u WHERE u.userId = :userId");
        $query->setParameters(array('userId' => $user->getUserId()));
        return $query->getResult();
    }
    
    
    public function getProjectComments(Project $project)
    {
        $query = $this->_em->createQuery("SELECT u FROM Application\Entity\Comment u WHERE u.projectId = :projectId");
        $query->setParameters(array('projectId' => $project->getProjectId()));
        return $query->getResult();
    }
}